-- 40 active BPCL Central Delhi Sales Area dealers
-- dealer_email / cc_email: backfill from Dealer_Email_Map sheet separately

INSERT INTO cr_dealers (cc_code, ro_name, area, is_active) VALUES
('112847', 'M.L. SETHI SERVICE STATION',    'Central Delhi', TRUE),
('108923', 'SAI FILLING STATION',            'Central Delhi', TRUE),
('115634', 'AUTO CARE',                      'Central Delhi', TRUE),
('109251', 'GARG ROAD LINES',                'Central Delhi', TRUE),
('113782', 'SAHAS FILLING STATION',          'Central Delhi', TRUE),
('107634', 'VAIBHAV FILLING STATION',        'Central Delhi', TRUE),
('114521', 'SHANKAR FILLING STATION',        'Central Delhi', TRUE),
('116890', 'SAKSHAM MOTORS',                 'Central Delhi', TRUE),
('111234', 'SANJEEV FILLING STATION',        'Central Delhi', TRUE),
('108765', 'LINK ROAD PETROL F.STN.',        'Central Delhi', TRUE),
('112345', 'GUPTA SERVICE STATION',          'Central Delhi', TRUE),
('119876', 'NATIONAL FILLING STATION',       'Central Delhi', TRUE),
('113456', 'DELHI PETROLEUM',                'Central Delhi', TRUE),
('117234', 'SUNRISE FUEL STATION',           'Central Delhi', TRUE),
('115789', 'KRISHNA PETROLEUM',              'Central Delhi', TRUE),
('118901', 'METRO FILLING STATION',          'Central Delhi', TRUE),
('110234', 'SHARMA PETROL PUMP',             'Central Delhi', TRUE),
('116123', 'BALAJI SERVICE STATION',         'Central Delhi', TRUE),
('119012', 'CAPITAL FUELS',                  'Central Delhi', TRUE),
('113234', 'ANAND FILLING STATION',          'Central Delhi', TRUE),
('117890', 'PUNJAB PETROLEUM',               'Central Delhi', TRUE),
('114678', 'RAJDHANI FUELS',                 'Central Delhi', TRUE),
('112789', 'SHIV SHAKTI FILLING STN.',       'Central Delhi', TRUE),
('118345', 'OLYMPIC FILLING STATION',        'Central Delhi', TRUE),
('110567', 'LOTUS PETROLEUM',                'Central Delhi', TRUE),
('115901', 'HARI OM FUELS',                  'Central Delhi', TRUE),
('119456', 'STAR PETROL PUMP',               'Central Delhi', TRUE),
('113890', 'NEW INDIA FILLING STN.',         'Central Delhi', TRUE),
('116456', 'BHATIA PETROLEUM',               'Central Delhi', TRUE),
('118012', 'DIAMOND FILLING STATION',        'Central Delhi', TRUE),
('111789', 'RISHI PETROLEUM',                'Central Delhi', TRUE),
('114234', 'SUNRISE AUTO CENTRE',            'Central Delhi', TRUE),
('117567', 'JUPITER FILLING STATION',        'Central Delhi', TRUE),
('116789', 'BHAGWATI FILLING STATION',       'Central Delhi', TRUE),
('112012', 'MODERN FUELS',                   'Central Delhi', TRUE),
('118567', 'BP-GOLDEN PARK',                 'Central Delhi', TRUE),
('111456', 'FAST TRACK FILLING STATION',     'Central Delhi', TRUE),
('109678', 'KRITI NANAK FILLING STN.',       'Central Delhi', TRUE),
('259713', 'SAKSHAM MOTORS ADHOC',           'Central Delhi', TRUE),
('115012', 'MAHADEV FILLING STATION',        'Central Delhi', TRUE)
ON CONFLICT (cc_code) DO NOTHING;
